dakshsinghrathore/ISRO-web

CSS/style.css
JS/script.js
index.html

This PR  Added the new vertical navbar that includes (launches, missions, updates, and careers)

Feat: added the feature menu vertical navbar

---

COMMU.html
CSS/style.css
Foreign.html
GSLV.html
LVM3.html
PSLV.html
index.html

add foreign satelite page and changes some data which was there as 0

---

CSS/style.css

Snap-Scrolling on the ISRO-web homepage

---

COMMU.html
Foreign.html
GSLV.html
JS/script.js
LVM3.html
PSLV.html
README.md

Earlier script was inside head tag due to which script was not rendered properly , moved it to the bottom . . 
Besides that , updated ```countUp()``` so that all the numbers load at the same time , regardless of their values making for a smooth animation

moved script tag and updated countUp() function

---

.vscode/settings.json
CSS/style.css

I have made the changes as mentioned in previous PR.
Thank you assigning me this.
closes #33

navbar UI changes

---

CSS/style.css
Foreign.html

Fixed: #43 
Updated website font to SpaceX like.
New font is looking a lot better and clean.
Comparing old font vs new font below:

feat: updated font to SpaceX like

---

Foreign/index.html
Mission.html
Updates/index.html
index.html

Closes https://github.com/dakshsinghrathore/ISRO-web/issues/58

feat : added instagram link

---

GSLV/index.html
LMV3/index.html
PSLV/index.html

LINKED THE SATELLITES TO THE OFFICIAL WEB PAGE OF ISRO

Links ADDED

---

CSS/style.css

There were some padding related issues in the _secondary navbar_ and _subscribe-toast_
So I fixed them

fix: fixed padding related Issue.

---

About/index.html
Careers/index.html
Communication-Satelites/index.html
Foreign/index.html
GSLV/index.html
LMV3/index.html
Mission.html
PSLV/index.html
Privacy/index.html
Updates/index.html
index.html

1. Added the secondary navbar to each page and updated their links as per need.
2. Moved the script to the correct Location in some files as it was not loading the script.

Feat: Added the Secondary navbar to each page and Updated links (issue: #79)

---

CSS/style.css

Center arrow

---

About/index.html
Careers/index.html
Communication-Satelites/index.html
Foreign/index.html
GSLV/index.html
LMV3/index.html
Mission.html
PSLV/index.html
Privacy/index.html
Updates/index.html

added favicon in all pages

---

index.html

removed the repetitive code

---

Careers/index.html

Removed an extra background image

Edited the Careers page

---

Privacy/index.html

Added the link to ISRO homepage and as soon as someone clicks on the logo, it will take them to the privacy page of ISRO.

Aakash isro homepage link

---

CSS/style.css
JS/script.js
index.html

This pull request addresses issue #99  where the menu icon was overlapping with navigation bar items on smaller screens. To resolve this issue, the following changes have been made:
Changes Made:
The navigation bar has been updated to provide an improved user experience on smaller screens. On larger screens, individual navigation tab items are displayed. On smaller screens, these items are now merged into a collapsible menu, accessible via a menu icon.
https://github.com/dakshsinghrathore/ISRO-web/assets/127736781/a98634bf-699a-470e-97c5-b6309b3082a7

Bugfixes overlapping of menu icon

---

Updates/index.html

Removed the extra page in updates section

fix: Fixed the extra page issue in updates section

---

Mission.html
Updates/index.html

[BUG]:Fixed all links in Updates and Missions page 

---

About/index.html
CSS/style.css
Careers/index.html
Communication-Satelites/index.html
Foreign/index.html
GSLV/index.html
Image_Gallery/index.html
LMV3/index.html
Mission.html
PSLV/index.html
Privacy/index.html
Updates/index.html
index.html

The UI glitch has been resolved with placing the onclick function to its parent element and adjusting the width of that element.
https://github.com/dakshsinghrathore/ISRO-web/assets/120103598/2139e0cc-deda-42de-bf71-ffccf7d4728d
The page is zoomed for better view.

fix: Resolve the hamburger issue . (Issue #57)

---

About/index.html
Careers/index.html
Communication-Satelites/index.html
Foreign/index.html
GSLV/index.html
Image_Gallery/index.html
LMV3/index.html
Mission.html
PSLV/index.html
Privacy/index.html
Updates/index.html
index.html

FIX #108
Updated all the twitter icons using the icon given in the issue

fix #108 Update twitter icon

---

Image_Gallery/index.html

BUG: ISRO logo in images page

---

CSS/style.css

Fix: Padding Issue

---

About/index.html
CSS/style.css
Careers/index.html
Communication-Satelites/index.html
Feedback/index.html
Foreign/index.html
GSLV/index.html
Image_Gallery/index.html
LMV3/index.html
Mission.html
PSLV/index.html
Privacy/index.html
Quiz/index.html
index.html

PR fixes: #98 
- I created a feedback form and
- added feedback button in the all forms of hamburger button sections 
**See below screenshot** 👇

create a feedback form

---

CSS/style.css
index.html

I have made some changes, Kindly see if they are visible tell me if I made some mistake and if it is not changed as I have just started contributing to open source.

fix: Arrow removed from inner div and in center

---

CSS/style.css
index.html

closes #147
update the UI of scroll to top component
No

update scroll up component

---

index.html

Added the Contact Us button in the footer of the webpage

Feat: Added Contact Us button

---

About/index.html
Careers/index.html
Communication-Satelites/index.html
Feedback/index.html
Foreign/index.html
GSLV/index.html
Image_Gallery/index.html
LMV3/index.html
Mission.html
PSLV/index.html
Privacy/index.html
Suppliers/suppliers.html
Updates/index.html

Before:
After:
#148 feature resolved

contact_us_icon for everypage 
